apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-code-with-quarkus
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-code-with-quarkus
    app.kubernetes.io/part-of: load-app-fe080161-8cc8-4ba3-b7c2-22565c033cc0
  name: devfile-sample-code-with-quarkus
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: devfile-sample-code-with-quarkus
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: devfile-sample-code-with-quarkus
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/test-rhtap-41-tenant/load-app-fe080161-8cc8-4ba3-b7c2-22565c033cc0/devfile-sample-code-with-quarkus@sha256:eea213ef3c66155648e89463ac692e7f4179db9ee6614de4401253e4cfcb8057
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
